# -*- coding: utf-8 -*-

# Module to handle i18n

import os
import gettext

# Initialize gettext
gettext_domain = 'turpial'
# localedir definition in development mode
if os.path.isdir(os.path.join(os.path.dirname(__file__), '..', 'i18n')):
    localedir = os.path.realpath(os.path.join(os.path.dirname(__file__), '..', 'i18n'))
    trans = gettext.install(gettext_domain, localedir)
    log.debug('LOCALEDIR: %s' % localedir)
else:
    trans = gettext.install(gettext_domain)

STRINGS = {
    'welcome': _('Welcome!'),
    'twitter': 'Twitter',
    'identica': 'Identi.ca',
    'add_new_account': _('Add a new account to start using Turpial'),
    'add_some_columns': _('You have accounts registered, now add some columns'),
    'update_status': _('Update status'),
    'send_direct_message': _('Send direct message'),
    'open_preferences_dialog': _('Open preferences dialog'),
    'about_turpial': _('About Turpial'),
    'add_columns': _('Add columns'),
    'add_accounts': _('Add accounts'),
    'search': _('Search'),
    'account': _('Account'),
    'accounts': _('Accounts'),
    'authorize_turpial': _('Authorize Turpial'),
    'type_the_pin': _('Type the PIN'),
    'save': _('Save'),
    'copy_the_pin': _('Authorize Turpial and copy the PIN in the text box'),
    'user_profile': _("User Profile"),
    'bio': _("Bio"),
    'location': _("Location"),
    'web': _("Web"),
    'tweets': _('Tweets'),
    'following': _('Following'),
    'followers': _('Followers'),
    'favorites': _('Favorites'),
    'criteria': _('Criteria'),
    'criteria_tooltip': _('Use hashtags, mentions or any text you want as search criteria'),
    'select_friend': _('Select friend'),
    'select': _('Select'),
    'load_friends_list': _('Load friends list'),
    'whats_happening': _("What's happening?"),
    'upload_image': _("Upload image"),
    'short_urls': _("Short URLs"),
    'update': _('Update'),
    'delete_column': _("Delete Column"),
    'now': _("now"),
    'retweeted_by': _("Retweeted by"),
    'new': _('New'),
    'delete': _('Delete'),
    'register_a_new_account': _('Register a new account'),
    'delete_an_existing_account': _('Delete an existing account'),
    'register_a_twitter_account': _('Register a Twitter account'),
    'register_an_identica_account': _('Register an Identi.ca account'),
    'no_registered_accounts': _('No registered accounts'),
    'broadcast': _('Broadcast'),
    'you_can_not_submit_an_empty_message': _("You can not submit an empty message"),
    'message_too_long_it_looks_like_a_testament': _("Message too long, it looks like a testament"),
    'in_reply_to': _("In reply to"),
    'reply': _('Reply'),
    'quote': _('Quote'),
    'retweet': _('Retweet'),
    'mark_as_favorite': _('Mark as favorite'),
    'unmark_as_favorite': _('Unmark as favorite'),
    'reply_to': _('Reply to'),
    'quoting': _('Quoting'),
    'confirm_retweet': _('Confirm Retweet'),
    'do_you_want_to_retweet_status': _('Do you want to retweet this status to all your friends?'),
    'confirm_delete': _('Confirm Delete'),
    'do_you_want_to_delete_status': _('Do you want to delete this status?'),

    #'no_registered_columns': ,
    #'preferences': _('Preferences'),
    #'reply_status': _('Reply status'),
    #'add_account': _('Add account'),
    #'columns': _('Columns'),
    #'column': _("Column"),
    #'create_account': _('Create Account'),
    #'login': _('Login'),
    #'add': _('Add'),
    #'retweeted': _('Retweeted'),
    #'redent': _('Redent'),
    #'redented': _('Redented'),
    #'favorited': _('Favorited'),
    #'view_conversation': _('View conversation'),
    #'show_all': _('Show all'),
    #'tweet': _('Tweet'),
    #'new_tweet': _('New Tweet'),
    #'new_tweets': _('New Tweets'),
    #'dent': _('Dent'),
    #'dents': _('Dents'),
    #'new_dent': _('New Dent'),
    #'new_dents': _('New Dents'),
    #'posts': _('Posts'),
    #'exit': _('Quit'),
    #'user': _('User'),
    #'password': _('Password'),
    #'user_and_password': _('User and password'),
    #'protocol': _('Protocol'),
    #'close': _('Close'),
    #'signin': _('Sign In'),
    #'save': _('Save'),
    #'ok': _('Ok'),
    #'accept': _('Accept'),
    #'cancel': _('Cancel'),
    #'public_timeline': _('Public Timeline'),
    #'saving': _('Saving...'),
    #'loading': _('Loading...'),
    #'connecting': _('Connecting...'),
    #'authenticating': _('Authenticating...'),
    #'authorizing': _('Authorizing...'),
    #'secure_auth': _('Secure Authentication'),
    #'login_cancelled': _('Login cancelled by user'),
    #'invalid_pin': _('You must write a valid PIN'),
    #'delete_account_confirm': _("Do you really want to delete the account "),
    #'delete_column_confirm': _("Do you really want to delete the column "),
    #'fields_cant_be_empty': _("Fields can't be empty"),
    #'from': _("from"),
    #'people': _("people"),
    #'person': _("person"),
    #'no_column_yet': _("There are no available columns because I'm still logging in"),
    #'retweeting': _("Retweeting..."),
    #'unretweeting': _("Undoing retweet..."),
    #'successfully_retweeted': _("Status successfully retweeted"),
    #'retweet_successfully_undone': _("Retweet successfully undone"),
    #'successfully_deleted': _("Status sucessfully deleted"),
    #'adding_to_fav': _("Adding to favorites..."),
    #'removing_from_fav': _("Removing from favorites..."),
    #'deleting': _("Deleting..."),
    #'short': _("Short"),
    #'image': _("Image"),
    #'select_account_to_post': _("Select accounts to post"),
    #'updating_status': _("Updating status..."),
    #'error_posting_to': _("Error posting to %s"),
    #'manual_update': _("Manual Update"),
    #'in_progress': _("In progress..."),
    #'logged_in': _("Logged In"),
    #'turpial_follow': _("Turpial (Follow)"),
    #'turpial_unfollow': _("Turpial (Unfollow)"),
    #'you_are_now_following': _("You are now following @%s"),
    #'you_are_no_longer_following': _("You are no longer following @%s"),
    #'message': _("Message"),
    #'follow': _('Follow'),
    #'unfollow': _('Unfollow'),
    #'requested': _("Requested"),
    #'mute': _("Mute"),
    #'unmute': _("Unmute"),
    #'block': _("Block"),
    #'spam': _("Spam"),
    #'reporting_as_spam': _("Reporting as spam"),
    #'user_reported_spam_successfully': _("User reported as spam successfully"),
    #'blocking_user': _("Blocking user..."),
    #'user_blocked_successfully': _("User blocked successfully"),
    #'this_is_you': _("This is you!"),
    #'following_user': _('Following user...'),
    #'unfollowing_user': _('Unfollowing user...'),
    #'you_are_now_following': _("You are now following @%s"),
    #'you_are_no_longer_following': _("You are no longer following @%s"),
    #'muting_user': _('Muting user...'),
    #'unmuting_user': _('Unmuting user...'),
    #'user_muted_successfully': _('User muted successfully'),
    #'user_unmuted_successfully': _('User unmuted successfully'),
    #'add_friend': _('Add friend'),
    #'loading_friends': _('Loading friends...'),
    #'friends': _('friends'),
    #'friend': _('friend'),
    #'friends_loaded_successfully': _('Friends loaded successfully'),
    #'shorting_urls': _('Shorting URLs...'),
    #'direct_messages': _('Direct Messages'),
    #'direct_message': _('Direct Message'),
    #'send_message_to': _('Send message to'),
    #'can_send_message_to_one_account': _("Wait! I just can send messages to \
    #one account at once"),
    #'sending_message': _('Sending message...'),
    #'direct_message_sent_successfully': _('Direct message sent successfully'),
    #'image_preview': _("Image Preview"),
    #'general': _('General'),
    #'notifications': _('Notifications'),
    #'services': _('Services'),
    #'web_browser': _('Web Browser'),
    #'filters': _('Filters'),
    #'proxy': _('Proxy'),
    #'advanced': _('Advanced'),
    #'delete_all_images_in_cache': _('Delete all images in cache'),
    #'restore_config_warning': _('This action will close Turpial and will \
    #delete your current config (you must start Turpial again). Do you want to \
    #continue?'),
    #'view_profile': _('View profile'),
    #'search_profile_in': ('Search profile in'),
    #'profiles': _('Profiles'),
    #'sound': _('Sound'),
    #'notificate': _('Notificate'),
    #'confirm_undo_retweet': _('Confirm Undo Retweet'),
    #'do_you_want_to_undo_repeat_status': _('Do you want to undo this repeat?'),
    #'do_you_want_to_delete_direct_message': _('Do you want to delete this direct message?'),
    #'confirm_unfollow': _('Confirm Unfollow'),
    #'do_you_want_to_unfollow_user': _('Do you want to unfollow @%s?'),
    #'confirm_discarad': _('Confirm Discard'),
    #'do_you_want_to_discard_message': _('Do you want to discard this message?'),
    #'error_loading_image': _('Error loading image'),
    #'credentials_could_not_be_empty': _('Credentials could not be empty'),
    #'file_not_found': _("File not found"),
    #'about_description': _('Microblogging client written in Python'),
    #'i_couldnt_update_status': _("Oh oh... I couldn't update your status"),
    #'url_already_short': _('URL already short'),
    #'no_url_to_short': _('There are no URLs to short'),
    #'couldnt_shrink_urls': _("Oops... I couldn't shrink all URLs"),
    #'criteria': _('Criteria'),
    #'this_search_support_advanced_operators': _('This search supports advanced operators like:'),
    #'for_more_information_visit': _('For more information visit'),
    #'twitter_search_documentation': _('Twitter Search Documentation'),
    #'error_loading_profile': _('Error loading profile'),
    #'reply_message_to': _('Reply message to'),
    #'less_than_a_minute': _('Less than a minute'),
    #'minute_ago': _('minute ago'),
    #'minutes_ago': _('minutes ago'),
    #'hour_ago': _('hour ago'),
    #'hours_ago': _('hours ago'),
}

class i18n:
    @staticmethod
    def get(key):
        try:
            return STRINGS[key]
        except KeyError:
            return key
